Create VOs, Config(ComplexProperty), adding fields to constructors Volunteer and Pet
Kerry333/Kind_heart pull request #8
Opened 2024-08-24 17:10 UTC by Kerry333

2024-08-24 17:47 UTC, YADARAN1 requested changes

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.API/Program.cs
> +builder.Services.AddScoped<ApplicationDbContext>();
Удалить ненужный код

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/Models/Pet.cs
> +    private Pet(PetId petId, Name name, Description description,
Каждый параметр на своей новой строке

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/Models/Pet.cs
> +    public static Result<Pet> Create(PetId id, Name name, Description description,
Каждый параметр на своей новой строке + сделать валидацию

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/Models/Pet.cs
> +   /* public static (Pet? Pet, string? Error) Create(string name, string description)
Удалить, если не используешь

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/Models/Pet.cs
> +        var pet = new Pet(id, name, description,
Каждый параметр на своей новой строке + сделать валидацию

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/Models/Volunteer.cs
> +    private Volunteer(VolunteerId volunteerId ,
Каждый параметр на своей новой строке + сделать валидацию

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/Models/Volunteer.cs
> +    public static Result<Volunteer> Create(VolunteerId volunteerId,
Каждый параметр на своей новой строке

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +    public static Result<Address> Create(NotEmptyString country, NotEmptyString city, NotEmptyString streetName, int number, int zipCode)
Каждый параметр на своей новой строке

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +    private Address(NotEmptyString country, NotEmptyString city, NotEmptyString streetName, int number, int zipCode)
Каждый параметр на своей новой строке

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Experience.cs
> +    public float Value { get; }
Почему "Опыт" в формате числа с плавающей точкой? сделать int'ом

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.API/Controllers/WeatherForecastController.cs
> +public class WeatherForecastController: ControllerBase
Удалить контроллер, если он не тестовый конечно же

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/NotEmptyString.cs
> +public record NotEmptyString
Нет смысла делать 1 класс для валидации свойства в другом

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/NotEmptyStringLong.cs
> +public record NotEmptyStringLong
Здесь тоже

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +    public NotEmptyString Country { get; } = default!;
Это что?

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +    public NotEmptyString City { get; } = default!;
И это?

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Surname.cs
> +public record Surname
Засунуть всё в 1 VO нет смысла разделять ФИО по одиночке

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Name.cs
> +public record Name
Засунуть всё в 1 VO нет смысла разделять ФИО по одиночке + добавь отчество, но сделай, что его необязательно указывать

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Infrastructure/Configurations/PetConfiguration.cs
> +            pb.ToJson();
Здесь в скобках указать название requisite_details

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Infrastructure/Configurations/PetConfiguration.cs
> +            pb.ToJson();
Тут тоже указать название

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Infrastructure/Configurations/VolunteerConfiguration.cs
> +            vb.ToJson();
Тут тоже указать название

2024-08-24 17:47 UTC, YADARAN1 commented on src/Kind_heart.Infrastructure/Configurations/VolunteerConfiguration.cs
> +            vb.ToJson();
Тут тоже указать название

2024-08-24 18:52 UTC, Kerry333 commented on src/Kind_heart.Domain/Models/Pet.cs
> +   /* public static (Pet? Pet, string? Error) Create(string name, string description)
Это я хочу пока оставить для себя (как часть учебного материала), когда проект буду завершать - тогда удалю эту часть

2024-08-25 07:02 UTC, YADARAN1 requested changes

2024-08-25 07:02 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/FullName.cs
> +    public Name FirstName { get; }  // так как record Name я создавала и для Pet, то почему бы его здесь не использовать
Мы можем делить только реквизиты, т.к. они у нас одинаковые, а имя у животного и имя у человека это разное(навряд-ли у животного может быть фамилия и отчество)

2024-08-25 07:02 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/FullName.cs
> +    public Name LastName { get; }
Отчество может быть необязательным, то есть nullable

2024-08-25 07:02 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +        if(string.IsNullOrWhiteSpace(country) || country.Length > Constants.MAX_LOW_TEXT_LENGTH)
Доделать валидацию

2024-08-25 08:11 UTC, Kerry333 commented on src/Kind_heart.Domain/ValueObjects/FullName.cs
> +    public Name FirstName { get; }  // так как record Name я создавала и для Pet, то почему бы его здесь не использовать
Я не очень поняла - почему нельзя использовать Name как базу? Для животного это будет просто кличка (кстати , частенько дают животным человеческие имена: кошка Маруся, например), а в создании имени и фамилии человека использовать Name как базу, почему нет? Для отчества я использую string, то есть оно не имеет отношения к животному

2024-08-25 08:25 UTC, Kerry333 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +        if(string.IsNullOrWhiteSpace(country) || country.Length > Constants.MAX_LOW_TEXT_LENGTH)
не очень поняла - что именно доделать? вроде бы все поля проверяются, или что-то дополнительно надо? подскажи., пожалуйста

2024-08-25 08:31 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +        if(string.IsNullOrWhiteSpace(country) || country.Length > Constants.MAX_LOW_TEXT_LENGTH)
Не все поля проверяются, тот же zipcode

2024-08-25 08:34 UTC, Kerry333 commented on src/Kind_heart.Domain/ValueObjects/Address.cs
> +        if(string.IsNullOrWhiteSpace(country) || country.Length > Constants.MAX_LOW_TEXT_LENGTH)
как это? все поля проверяются , и zipcode проверяется :  
if (zipCode <= 0 )
            return Result.Failure<Address>("HouseNumber must be a positive number.");

2024-08-25 08:35 UTC, YADARAN1 commented on src/Kind_heart.Domain/ValueObjects/FullName.cs
> +    public Name FirstName { get; }  // так как record Name я создавала и для Pet, то почему бы его здесь не использовать
А разве кличка это не имя? Name как базу использовать можно, но смысла особого нет, этот подход помогает более чётко структурировать данные и лучше отражает различия между этими типами сущностей в вашем приложении. А отчество(LastName?) оно должно быть таким, потому-что у человека не может быть отчества

2024-08-25 08:43 UTC, Kerry333 commented on src/Kind_heart.Domain/ValueObjects/FullName.cs
> +    public Name FirstName { get; }  // так как record Name я создавала и для Pet, то почему бы его здесь не использовать
Я все равно не очень понимаю : если есть уже созданный record Name , почему нет смысла его использовать (это так же как и string, суть по идее одна - прописать имя и сделать валидацию). В моем понимании имя человека и имя для животного это , совсем грубо говоря, его идентификатор, то есть разницы нет.

2024-08-25 09:20 UTC, merged